### ISSUE TITLE
Tropical Fish Breeding issue

### ISSUE THREAD

**Issue by DrinkWaterALot** [Uraneptus/LetFishLove#2]
So whenever I breed tropical fish, all the babies that hatch are completely white, even when the parents have no white on them at all

Not sure if this is a issue with conflicting mods, or something else

**Comment by Uraneptus** [comment]
Which version of the mod are you using?

**Comment by DrinkWaterALot** [comment]
I am using 1.20.1 with the latest version of this mod

**Comment by Uraneptus** [comment]
Which other mods have you installed?

**Comment by DrinkWaterALot** [comment]
I have

- Cobblemon
- Cobblemon Intergrations
- Create
- Curios API
- Ferritecore
- HT's Treechop
- Immersive Aircraft
- Jade
- JEI
- Kotlin for  Forge
- Let fish love
- Optifine
- RightClickHarvest
- Sophisticated Backpacks
- Sophisticated Core
- Terrablender
- Terralith
- William Wythers Overhauled Overworld
- Xaero's minimap
- Xaero's Worldmap

also not sure if this has anything to do with it, but I changed around some configs (hatch times)

**Comment by VakyPanda** [comment]
same issue over here ( although i have a big modpack installed too, haven't tested in singleplayer/with the mod alone ) 
![2024-04-26_05 30 43](https://github.com/Uraneptus/LetFishLove/assets/63160430/383b180d-333b-4987-82c8-96e46f770e12)
![2024-04-26_05 31 48](https://github.com/Uraneptus/LetFishLove/assets/63160430/f2fd7383-644a-4f95-96bb-69b5eb68f4ba)
![2024-04-26_05 31 52](https://github.com/Uraneptus/LetFishLove/assets/63160430/8ed07cc1-0f79-46e4-a9a2-096c8e48528b)

**Comment by Uraneptus** [comment]
Sorry for the late response I was very busy the past months. I've looked into this and will upload a version that hopefully fixes this! (If it doesn't, lemme know)
